### ISSUE TITLE
Two exceptions thrown at the same time cause the program to hang

### ISSUE THREAD

**Issue by tgodzik** [softwaremill/ox#164]
This will print 1 and and then the InterruptedException in 2, while 3 will never show up and the whole application hangs.

```
@main def exceptionsOx() = 
  supervised:  
    def computation(withException: Option[String]): Int =
      sleep(2.seconds)
      withException match
        case None => 1
        case Some(value) =>
          throw new Exception(value)
    
    val fork1 = forkUser:
        computation(withException = None)
    val fork2 = forkUser:
        computation(withException = Some("Oh no!"))
    val fork3 = forkUser:
        computation(withException = Some("Oh well.."))
    println(fork1.joinEither()) // 1
    println(fork2.joinEither()) // 2
    println(fork3.joinEither()) // 3
```

This doesn't happen if we don't do a normal join. Is this an antipattern in ox? Looks like a very easy thing shot yourself with.

I mostly confused by the behaviour here.

**Comment by tgodzik** [comment]
Also, a very similar case:
```
@main def exceptionsOx() = 
  val res: Throwable | Unit = 
    supervisedError(ox.UnionMode[Throwable]()):  
      def computation(withException: Option[String]): Int =
        sleep(2.seconds)
        withException match
          case None => 1
          case Some(value) =>
            throw new Exception(value)
        
      val fork1 = forkError:
        computation(withException = None)
      val fork2 = forkError:
        computation(withException = Some("Oh no!"))
      val fork3 = forkError:
        computation(withException = Some("Oh well.."))
      println(fork1.join())
      println(fork2.join())
      println(fork3.join())
  println("Hello!")
  println(res)
```
never returns res, but throws the exception instead.

**Comment by tgodzik** [comment]
Ach, the second one is expected, but less fun than I thought. You actually have to return the value, while I thought it's a way to pack it.

**Comment by lbialy** [comment]
Fun:
```
"pool-1-thread-1-ScalaTest-running-SupervisedTest" #30 [43267] prio=5 os_prio=31 cpu=79.94ms elapsed=107.10s tid=0x0000000121860600 nid=43267 waiting on condition  [0x000000017373b000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.2/Native Method)
        at java.util.concurrent.locks.LockSupport.park(java.base@21.0.2/LockSupport.java:371)
        at jdk.internal.misc.ThreadFlock.close(java.base@21.0.2/ThreadFlock.java:423)
        at java.util.concurrent.StructuredTaskScope.close(java.base@21.0.2/StructuredTaskScope.java:836)
        at ox.unsupervised$package$.scopedWithCapability(unsupervised.scala:58)
        at ox.supervised$package$.supervisedError(supervised.scala:54)
        at ox.supervised$package$.supervised(supervised.scala:27)
 ```

**Comment by lbialy** [comment]
While docs state that `joinEither` should be only used in unsupervised scopes I would also expect this to work.

**Comment by lbialy** [comment]
This also happens with `fork` so not only `forkUser`.

**Comment by lbialy** [comment]
It looks like the whole thing is caused by `joinEither` catching `InterruptedException`s (haha, my suggestion). What happens is that there's an assumption that once the first exception terminates the whole supervised scope (via `DefaultSupervisor#forkException`) other joins will get interrupted and that's exactly what happens - `fork2.joinEither()` returns `Left(java.lang.InterruptedException)`. This means however that the virtual thread running the `supervised` body catches it's own interruption and happily marches on to `fork3.joinEither()` and hangs on `result.get()` there.

**Comment by lbialy** [comment]
So the big problem here is that `result.get()` where `result: CompletableFuture[T]` can throw `InterruptedException` both when the current thread (the one waiting on `result.get()`) and when the forked thread was interrupted and there's no easy way to discern between the two scenarios. We should not rethrow InterruptedException if it comes from the forked thread but we definitely should rethrow it if it's due to our thread being interrupted like in this case. 

The solution I think could work is to:
1) add this method to Fork:
`def wasInterrupted: Boolean`
2) general implementation for both `newForkUsingResult` and `forkCancellable` is: 
```scala
  override def wasInterrupted: Boolean =

    result.isCompletedExceptionally && result.exceptionNow().isInstanceOf[InterruptedException]
```
3) `joinEither` changes this way:
```scala
  def joinEither(): Either[Throwable, T] =
    try Right(join())
    catch
      // normally IE is fatal, but here it could have meant that the fork was cancelled, hence we catch it
      // we do discern between the fork and the current thread being cancelled and rethrow if it's us who's getting the axe
      case e: InterruptedException => if wasInterrupted then Left(e) else throw e
      case NonFatal(e)             => Left(e)
```

Opened PR #168 with fix.

**Comment by lbialy** [comment]
This solution is not bulletproof btw - it's entirely possible for both `Fork#wasInterrupted` to be true AND `supervised` body fork to be interrupted too and for the `InterruptedException` to be the one thrown due to body fork being interrupted. In that scenario I think this issue will reappear. I think this can be replicated quite easily. `result.get()` resets the `interrupted` flag on the body fork so there's no way for us to know for sure whether *our* fork was interrupted. Maybe we could use object identity and implement this `wasInterrupted` method as:
```
  override def wasInterruptedWith(ie: InterruptedException): Boolean =
    result.isCompletedExceptionally && result.exceptionNow() eq ie
```

What do you think @adamw?

**Comment by lbialy** [comment]
It's not easy to replicate the error condition I was think about, actually :|

**Comment by lbialy** [comment]
But on the other hand this:
```scala
  override def wasInterruptedWith(ie: InterruptedException): Boolean =
    result.isCompletedExceptionally && result.exceptionNow() eq ie
```

works as well.

**Comment by adamw** [comment]
Hm I think your solution with the identity check is fine. 

If the scope ends (i.e., all forks are interrupted), then there are three cases, when calling `fork.join()` from `fork.joinEither()`:

1. an IE will be thrown, and `result.exceptionNow()` returns `null` - meaning that the main body fork was interrupted. We then re-throw the IE
2. an IE is thrown, `result.exceptionNow()` returns the same (in terms of identity) exception - then it's the fork that was interrupted. We return a `Left`. The body's interruption status is untouched, and an IE will be thrown on the next blocking operation
3. an IE is thrown, `result.exceptionNow()` return a different exception - the main body fork was interrupted. We re-throw

Separately, maybe it would be possible to create a `UnsupervisedFork` trait which would have the `joinEither` method? Then, we could avoid accidental inproper usage, as in the original report.

**Comment by adamw** [comment]
Btw. I think I'd keep things such as `wasInterrupted` ox-private. At least until somebody finds a use-case to make it public ;)

**Comment by adamw** [comment]
of course you can use `joinEither` in supervised scopes, but it will only work (differently than `join()`) on unsupervised forks. That is: in a supervised scope, you can create both supervised & unsupervised forks. Maybe that's also confusing and we need better names ;)

**Comment by lbialy** [comment]
So for `UnsupervisedFork`, the result of `fork` in `unsupervised` block the impl of `joinEither` would catch IE as it was till now, just catch anything because there's no fork for the body that will get interrupted and then overridden impl for `Fork` would not catch `InterruptedException` at all and crash the whole supervised scope on any interruption, right? It sounds very reasonable but there's a catch I think:
```
scala> supervised:
     |   fork:
     |     sleep(5.millis)
     |     throw Exception("i'm gonna interrupt ya all")
     |
     |   fork:
     |     unsupervised:
     |       val safeForkEitherHuh = fork:
     |         sleep(60.millis)
     |         "nice"
     |       println("lol: " + safeForkEitherHuh.joinEither()) // will catch IE, won't it?
     |   ()
     |
lol: Left(java.lang.InterruptedException) // yes it does!
```

**Comment by lbialy** [comment]
In the meantime I've checked what happens on this patch branch in sbt console:
```scala
scala> supervised:
     |   fork:
     |     sleep(5.millis)
     |     throw Exception("i'm gonna interrupt ya all")
     |
     |   fork:
     |     unsupervised:
     |       val safeForkEitherHuh = fork:
     |         sleep(60.millis)
     |         "nice"
     |       println("lol: " + safeForkEitherHuh.joinEither()) // will catch IE, won't it?
     |       never
     |   "finished due to interrupt!"
     |
val res0: String = finished due to interrupt!
```

I would opt for precise semantics that `joinEither` always captures IE coming from the fork thread and rethrows IE from the thread that calls join() because it doesn't have such gotchas (I hope!).

**Comment by adamw** [comment]
WIth `UnsupervisedFork` we still need the mechanism of checking if the IE originated from the fork, or from interrupting the `join()`. You can still create unsupervised forks in supervised scopes (supervised scope == a supervisor is available, but you don't have to use it).

It's just that calling `.joinEither()` on a supervised scope doesn't have sense.

**Comment by lbialy** [comment]
is there anything that's still left to do in #168?

**Comment by adamw** [comment]
No, I think we're good. What is`Global / cancelable := true` doing?

**Comment by lbialy** [comment]
Ctrl+c won't kill sbt when you just want to interrupt a deadlock.

**Comment by adamw** [comment]
Thanks, added that as a comment

**Comment by adamw** [comment]
@lbialy it seems to be `true` by default, though?

**Comment by tgodzik** [comment]
Thanks for the fix! I didn't actually realize I found a valid issues :D I thought it was my experimentation that was doing something wrong.

**Comment by lbialy** [comment]
Hmmm, maybe this setting is not necessary anymore. Problem was that on a true deadlock sbt's jvm was non-responsive. Adding fork := true solves that. I just tried on a clean template with sbt 1.9.8 and it seems to work fine.
